name: Convert build files to APK and upload to Github Artifacts
on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

        

    - run: git clone https://github.com/cszwbirbwl/cszwbirbwl.github.io
    
 
    - uses: cyhycf/android_builder@main
      with:
          build-folder-path: "./cszwbirbwl.github.io" # Defaults to build, It is the folder where build files or html are stored
          app-name: "kjybj" # Defaults to MyApp
          output-folder-path: "my-apks" # Defaults to apk/, Where final APK files are created
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Final-apks
        path: my-apks/ # Should be same as "output-folder-path"
